GET http://localhost:8080/verify-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3OTM4Nzk4MTI3MzM4OTEzMDAsImlhdCI6MTY0NzQ2MDYzNywiZXhwIjoxNjQ3NDYyNDM3fQ.2UgBUD1JOaPPv4JU37tPGrVSS8loSstuQBTwC2cOoqA